/** Tailwind prose classes for public blog article HTML content. */
export const ARTICLE_PROSE_CLASS = [
  "blog-prose",
  "max-w-none",
  "text-[var(--foreground)]/90",
  "text-base leading-relaxed",
  "sm:text-[1.0625rem] sm:leading-[1.75]",
  "[&>p:first-of-type]:text-lg [&>p:first-of-type]:leading-relaxed [&>p:first-of-type]:text-[var(--color-brown-muted)]",
  "[&_h2]:mt-12 [&_h2]:mb-4 [&_h2]:scroll-mt-28 [&_h2]:font-display [&_h2]:text-2xl [&_h2]:font-semibold [&_h2]:tracking-tight [&_h2]:text-[var(--color-brown)]",
  "[&_h3]:mt-10 [&_h3]:mb-3 [&_h3]:scroll-mt-28 [&_h3]:font-display [&_h3]:text-xl [&_h3]:font-semibold [&_h3]:text-[var(--color-brown)]",
  "[&_h4]:mt-8 [&_h4]:mb-2 [&_h4]:font-display [&_h4]:text-lg [&_h4]:font-semibold [&_h4]:text-[var(--color-brown)]",
  "[&_p]:my-5 [&_p]:leading-[1.8]",
  "[&_a]:font-medium [&_a]:text-[var(--color-cta)] [&_a]:underline [&_a]:decoration-[var(--color-cta)]/30 [&_a]:underline-offset-[3px] hover:[&_a]:decoration-[var(--color-cta)]",
  "[&_blockquote]:my-8 [&_blockquote]:rounded-r-xl [&_blockquote]:border-l-4 [&_blockquote]:border-[var(--color-green)] [&_blockquote]:bg-[var(--secondary)]/40 [&_blockquote]:py-4 [&_blockquote]:pl-6 [&_blockquote]:pr-4 [&_blockquote]:italic [&_blockquote]:text-[var(--color-brown-muted)]",
  "[&_ul]:my-6 [&_ul]:list-disc [&_ul]:space-y-1 [&_ul]:pl-6 [&_ul]:marker:text-[var(--color-green)]",
  "[&_ol]:my-6 [&_ol]:list-decimal [&_ol]:space-y-1 [&_ol]:pl-6 [&_ol]:marker:font-semibold [&_ol]:marker:text-[var(--color-brown)]",
  "[&_li]:my-1.5 [&_li]:pl-1",
  "[&_code]:rounded-md [&_code]:bg-[var(--secondary)] [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:font-mono [&_code]:text-[0.875em] [&_code]:text-[var(--color-brown)]",
  "[&_pre]:my-8 [&_pre]:overflow-x-auto [&_pre]:rounded-xl [&_pre]:border [&_pre]:border-[var(--color-card-border)] [&_pre]:bg-[var(--color-brown)] [&_pre]:p-4 [&_pre]:text-sm [&_pre]:leading-relaxed [&_pre]:text-white [&_pre_code]:bg-transparent [&_pre_code]:p-0 [&_pre_code]:text-inherit",
  "[&_img]:my-8 [&_img]:rounded-xl [&_img]:border [&_img]:border-[var(--color-card-border)] [&_img]:shadow-sm",
  "[&_figure]:my-8",
  "[&_figcaption]:mt-2 [&_figcaption]:text-center [&_figcaption]:text-sm [&_figcaption]:text-[var(--muted-foreground)]",
  "[&_table]:my-8 [&_table]:w-full [&_table]:overflow-hidden [&_table]:rounded-xl [&_table]:border [&_table]:border-[var(--color-card-border)]",
  "[&_thead]:bg-[var(--secondary)]",
  "[&_th]:border-b [&_th]:border-[var(--color-card-border)] [&_th]:px-4 [&_th]:py-3 [&_th]:text-left [&_th]:text-sm [&_th]:font-semibold [&_th]:text-[var(--color-brown)]",
  "[&_td]:border-b [&_td]:border-[var(--color-card-border)] [&_td]:px-4 [&_td]:py-3 [&_td]:text-sm",
  "[&_tr:last-child_td]:border-b-0",
  "[&_hr]:my-12 [&_hr]:border-0 [&_hr]:border-t [&_hr]:border-[var(--color-card-border)]",
  "[&_strong]:font-semibold [&_strong]:text-[var(--color-brown)]",
].join(" ");
